package com.github.feelbeatapp.androidclient.error

enum class ErrorCode {
    AUTHORIZATION_SERVER_UNREACHABLE,
    AUTHORIZATION_ACCESS_TOKEN_ERROR,
    AUTHORIZATION_REFRESH_TOKEN_ERROR,
    AUTHENTICATION_LOGOUT_ERROR,
}
